# Generated by Django 3.2.8 on 2022-07-27 20:32

from django.db import migrations
from tdp.data_inicial import dataPersona, dataTrabajo, dataFlujo, dataProyecto


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Persona = apps.get_model('tdp', 'Persona')
    for persona in dataPersona:
        new_persona = Persona(      
            nombre = persona['nombre'],
            cargo = persona['cargo'],
            tipo = persona['tipo'],
        )
        new_persona.save()

    Proyecto = apps.get_model('tdp', 'Proyecto')
    for proyecto in dataProyecto:
        new_proyecto = Proyecto(   
            fkPersona = proyecto['fkPersona'],
            cliente = proyecto['cliente'],
            JP = proyecto['JP'],
            descripcion = proyecto['descripcion'],
            flujosTotal = proyecto['flujosTotal'],
            flujosResueltos = proyecto['flujosResueltos'],   
        )
        new_proyecto.save()

    Trabajo = apps.get_model('tdp','Trabajo')
    for trabajo in dataTrabajo:
        new_trabajo = Trabajo(
            fkFlujo = trabajo['fkFlujo'],
            fkPersona = trabajo['fkPersona'],
            trabajo = trabajo['trabajo'],
            responsable = trabajo['responsable'],
            estado_requiere = trabajo['estado_requiere'],
            estado_activo = trabajo['estado_activo'],
            estado_finalizado = trabajo['estado_finalizado'],
            informacion = trabajo['informacion'],
            sede = trabajo['sede'],
        )
        new_trabajo.save()

    Flujo = apps.get_model('tdp','Flujo')
    for flujo in dataFlujo:
        new_flujo = Flujo(
            fkProyecto = flujo['fkProyecto'],
            descripcion = flujo['descripcion'],
            coordenadas = flujo['coordenadas'],
            flujo = flujo['flujo'],
            conexion = flujo['conexion'],
        )
        new_flujo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tdp', '0006_auto_20220727_2016'),
    ]

    operations = [
        migrations.RunPython(combine_names),
]
