# Generated by Django 3.2.8 on 2022-07-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkProyecto', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('coordenadas', models.JSONField()),
                ('flujo', models.JSONField()),
                ('conexion', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('cargo', models.CharField(default='', max_length=50)),
                ('tipo', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkPersona', models.IntegerField(default=0)),
                ('cliente', models.CharField(default='', max_length=50)),
                ('JP', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('flujosTotal', models.IntegerField(default=0)),
                ('flujosResueltos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkFlujo', models.IntegerField(default=0)),
                ('fkPersona', models.IntegerField(default=0)),
                ('trabajo', models.CharField(default='', max_length=50)),
                ('responsable', models.CharField(default='', max_length=50)),
                ('estado_requiere', models.IntegerField(default=0)),
                ('estado_activo', models.IntegerField(default=0)),
                ('estado_finalizado', models.IntegerField(default=0)),
                ('informacion', models.CharField(default='', max_length=50)),
                ('sede', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
