# Generated by Django 4.0.4 on 2022-05-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flujo',
            old_name='first_name',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='first_name',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='first_name',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='flujo',
            name='last_name',
        ),
    ]
