# Generated by Django 3.0.8 on 2020-07-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cliente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
