# Generated by Django 3.0.8 on 2020-07-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200705_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_trabajo', models.CharField(max_length=200)),
                ('datos_tecnicos', models.CharField(max_length=200)),
                ('tipo_de_accceso', models.CharField(max_length=200)),
                ('instalacion_cliente', models.CharField(max_length=200)),
            ],
        ),
    ]
