# Generated by Django 3.0.8 on 2020-07-06 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='coordenada_latitud',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='coordenada_longitud',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='foreign_key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Proyecto'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='datos_tecnicos',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sede',
            name='descripcion_trabajo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sede',
            name='instalacion_cliente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sede',
            name='tipo_de_accceso',
            field=models.CharField(default='', max_length=200),
        ),
    ]
