# Generated by Django 3.0.8 on 2020-07-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200705_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='foreign_key',
            new_name='llave_foranea',
        ),
    ]
