# Generated by Django 3.0.8 on 2020-07-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200705_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='llave_foranea',
        ),
    ]
