# Generated by Django 3.0.8 on 2020-07-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_sede_llave_foranea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
