# Generated by Django 3.0.8 on 2020-07-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_delete_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('descripcion_trabajo', models.CharField(default='', max_length=200)),
                ('datos_tecnicos', models.CharField(default='', max_length=200)),
                ('tipo_de_accceso', models.CharField(default='', max_length=200)),
                ('instalacion_cliente', models.CharField(default='', max_length=200)),
                ('coordenada_latitud', models.IntegerField(default=0)),
                ('coordenada_longitud', models.IntegerField(default=0)),
            ],
        ),
    ]
