# Generated by Django 3.0.8 on 2020-07-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='coordenada_latitud',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='coordenada_longitud',
        ),
    ]
