# Generated by Django 3.0.8 on 2020-07-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200705_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='aa',
            field=models.CharField(default='', max_length=200),
        ),
    ]
