# Generated by Django 3.0.8 on 2020-07-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_sede_aa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
