# Generated by Django 3.0.8 on 2020-07-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200705_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('cliente', models.CharField(default='', max_length=200)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('tipo', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(verbose_name='date published')),
                ('fecha_fin', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('descripcion_trabajo', models.CharField(default='', max_length=200)),
                ('datos_tecnicos', models.CharField(default='', max_length=200)),
                ('tipo_de_accceso', models.CharField(default='', max_length=200)),
                ('instalacion_cliente', models.CharField(default='', max_length=200)),
                ('aa', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
