# Generated by Django 3.0.8 on 2020-07-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_proyecto_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='llave_forenea',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
