# Generated by Django 3.0.8 on 2020-07-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_sede_llave_forenea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='llave_forenea',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='polls.Proyecto'),
        ),
    ]
