# Generated by Django 3.0.8 on 2020-07-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200705_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='aa',
        ),
    ]
