# Generated by Django 3.0.8 on 2020-07-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_remove_sede_aa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='coordenada_latitud',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='coordenada_longitud',
            field=models.IntegerField(default=0),
        ),
    ]
