# Generated by Django 3.0.8 on 2020-07-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20200705_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='jp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
