# Generated by Django 3.0.8 on 2020-07-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20200706_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='instalacion_cliente',
            new_name='contrata_acceso',
        ),
        migrations.AddField(
            model_name='sede',
            name='contrata_equipo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sede',
            name='equipamiento',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sede',
            name='situacion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
