# Generated by Django 3.0.8 on 2020-07-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20200706_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='sedes_pendientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sedes_total',
            field=models.IntegerField(default=0),
        ),
    ]
