# Generated by Django 3.0.8 on 2020-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20200706_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='foto_alcance',
            field=models.ImageField(default='proyecto.jpg', upload_to='cars'),
        ),
    ]
