# Generated by Django 3.0.8 on 2020-07-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_proyecto_foto_alcance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('VP', 'virtual private network'), ('IN', 'infointernet'), ('SI', 'SIP trunk')], default='VP', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='sede',
            name='coordenada_latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sede',
            name='coordenada_longitud',
            field=models.FloatField(default=0),
        ),
    ]
