# Generated by Django 3.0.8 on 2020-07-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20200709_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='year_in_school',
            new_name='servicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='acceso',
            field=models.CharField(choices=[('FO', 'Fibra optica'), ('CU', 'cobre'), ('3G', 'movil_3G'), ('RU', 'satelital')], default='FO', max_length=2),
        ),
        migrations.AddField(
            model_name='servicio',
            name='datos_tecnicos',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('AN', 'alta nueva'), ('RU', 'rutina')], default='AN', max_length=2),
        ),
    ]
