# Generated by Django 3.0.8 on 2020-07-10 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20200709_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='llave_forenea',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='polls.Sede'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='acceso',
            field=models.CharField(choices=[('FO', 'Fibra optica'), ('CU', 'cobre'), ('3G', 'movil 3G'), ('4G', 'movil 4G'), ('RU', 'satelital'), ('OT', 'otro')], default='FO', max_length=2),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='datos_tecnicos',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(choices=[('VP', 'virtual private network'), ('IN', 'infointernet'), ('SI', 'SIP trunk'), ('OT', 'otro')], default='VP', max_length=2),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('AN', 'alta nueva'), ('RU', 'rutina'), ('OT', 'otro')], default='AN', max_length=2),
        ),
    ]
