# Generated by Django 3.0.8 on 2020-07-10 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20200709_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio_TCP_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_fisica', models.BooleanField(default=False)),
                ('capa_acceso', models.BooleanField(default=False)),
                ('capa_red', models.BooleanField(default=False)),
                ('capa_trasporte', models.BooleanField(default=False)),
                ('capa_aplicacion', models.BooleanField(default=False)),
                ('datos_capa_fisica', models.TextField(default='')),
                ('datos_capa_red', models.TextField(default='')),
                ('datos_capa_trasporte', models.TextField(default='')),
                ('datos_capa_aplicacion', models.TextField(default='')),
                ('llave_forenea', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='polls.Sede')),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
