# Generated by Django 3.0.8 on 2020-07-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200709_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='datos_capa_acceso',
            field=models.TextField(default=''),
        ),
    ]
