# Generated by Django 3.0.8 on 2020-07-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20200712_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='nombre_servicio',
            field=models.CharField(default='', max_length=200),
        ),
    ]
