# Generated by Django 3.0.8 on 2020-07-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_servicio_tcp_ip_nombre_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='avance',
            field=models.FloatField(default=0),
        ),
    ]
