# Generated by Django 3.0.8 on 2020-07-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_servicio_tcp_ip_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='estado_capa_acceso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='estado_capa_aplicacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='estado_capa_fisica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='estado_capa_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='estado_capa_trasporte',
            field=models.BooleanField(default=False),
        ),
    ]
