# Generated by Django 3.0.8 on 2020-07-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20200722_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_tecnicos', models.TextField(default='')),
                ('coordenada_longitud', models.FloatField(default=0)),
                ('coordenada_latitud', models.FloatField(default=0)),
                ('equipo', models.CharField(choices=[('PE', 'equipo_pe'), ('CE', 'equipo_ce'), ('DE', 'demarcador'), ('RE', 'recurso_empresarial'), ('RM', 'recurso_metro'), ('TR', 'transimision')], default='CE', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='sede',
            name='datos_tecnicos',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='descripcion_trabajo',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='equipamiento',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='tipo_de_accceso',
        ),
        migrations.AlterField(
            model_name='sede',
            name='contrata_acceso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sede',
            name='contrata_equipo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sede',
            name='situacion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
