# Generated by Django 3.0.8 on 2020-07-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20200722_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio_tcp_ip',
            old_name='capa_acceso',
            new_name='activo_capa_acceso',
        ),
        migrations.RenameField(
            model_name='servicio_tcp_ip',
            old_name='capa_aplicacion',
            new_name='activo_capa_aplicacion',
        ),
        migrations.RenameField(
            model_name='servicio_tcp_ip',
            old_name='capa_fisica',
            new_name='activo_capa_fisica',
        ),
        migrations.RenameField(
            model_name='servicio_tcp_ip',
            old_name='capa_red',
            new_name='activo_capa_red',
        ),
        migrations.RenameField(
            model_name='servicio_tcp_ip',
            old_name='capa_trasporte',
            new_name='activo_capa_trasporte',
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='responsable_capa_acceso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='responsable_capa_aplicacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='responsable_capa_fisica',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='responsable_capa_red',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio_tcp_ip',
            name='responsable_capa_trasporte',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio_tcp_ip',
            name='nombre_servicio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
