# Generated by Django 3.0.8 on 2020-07-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20200722_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='prueba',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='puesto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='jp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
