# Generated by Django 3.0.8 on 2020-10-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_auto_20201030_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_geojson',
            name='color',
            field=models.CharField(choices=[('RO', 'rojo'), ('VE', 'verde'), ('AZ', 'azul'), ('AM', 'amarillo')], default='RO', max_length=2),
        ),
        migrations.AlterField(
            model_name='interface_geojson',
            name='informacion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='interface_geojson',
            name='tipo_de_geojson',
            field=models.CharField(choices=[('SP', 'Point'), ('MP', 'MultiPoint'), ('SL', 'LineString'), ('ML', 'MultiLineString'), ('SG', 'Polygon'), ('MG', 'MultiPolygon'), ('GC', 'GeometryCollection')], default='SP', max_length=2),
        ),
    ]
