# Generated by Django 3.0.8 on 2020-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20201031_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio_TCP_IP',
            new_name='Trabajo',
        ),
        migrations.AlterField(
            model_name='interface_geojson',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('yellow', 'yellow')], default='RE', max_length=6),
        ),
    ]
