# Generated by Django 3.0.8 on 2021-03-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_auto_20201109_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interface_geojson',
            new_name='InterfaceGeojson',
        ),
    ]
