# Generated by Django 4.0.3 on 2022-03-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_auto_20210228_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='nombre_servicio',
            field=models.CharField(choices=[('T0', 'no se hara'), ('T1', 'configuracion IP LAN'), ('T2', 'doble operador'), ('T3', 'firewall local'), ('T4', 'infointernet'), ('T5', 'QoS'), ('T6', 'redundancia capa 3')], default='SP', max_length=2),
        ),
    ]
