# Generated by Django 4.0.3 on 2022-03-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_alter_trabajo_nombre_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacegeojson',
            name='llave_forenea',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='polls.proyecto'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='datos_capa_acceso',
            field=models.TextField(default='no hay datos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='datos_capa_aplicacion',
            field=models.TextField(default='no hay datos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='datos_capa_fisica',
            field=models.TextField(default='no hay datos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='datos_capa_red',
            field=models.TextField(default='no hay datos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='datos_capa_trasporte',
            field=models.TextField(default='no hay datos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='responsable_capa_acceso',
            field=models.CharField(default='no hay responsable', max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='responsable_capa_aplicacion',
            field=models.CharField(default='no hay responsable', max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='responsable_capa_fisica',
            field=models.CharField(default='no hay responsable', max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='responsable_capa_red',
            field=models.CharField(default='no hay responsable', max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='responsable_capa_trasporte',
            field=models.CharField(default='no hay responsable', max_length=100),
        ),
    ]
